source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Neuron_Example', :exclusive => true do
  pod "Neuron", :path => "../"
end

target 'Neuron_Tests', :exclusive => true do
  pod "Neuron", :path => "../"

  
end
